server:
  contextPath: /api
  port: 8081
  compression:
    enabled: true
    mimeTypes: text/html,text/xml,text/plain,application/json,application/xml

spring:
  jackson:
    mapper.default_view_inclusion: false
    serialization:
      write_dates_as_timestamps: false
      write_bigdecimal_as_plain: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chords
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        format_sql: false
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
  data:
    solr:
      host: http://localhost:8983/solr/chords-core
  social:
    facebook:
      app-id: 1086354088118124
      app-secret: ${FACEBOOK_APP_SECRET}

jwt:
  header: Authorization
  scheme: Bearer
  secret: ${JWT_SECRET}
  expiration: 60000

flyway:
  db:
    clean: ${flyway.clean:false}

endpoints.enabled: false

endpoints:
  info.enabled: true
  health.enabled: true

logging:
  level:
    com.robotnec.chords: DEBUG
    org.springframework.web: WARN
    org.hibernate: WARN
    ma.glasnost.orika: WARN



