server:
  contextPath: /api
  port: 8081
  compression:
    enabled: true
    mimeTypes: text/html,text/xml,text/plain,application/json,application/xml

logging:
  config: classpath:logback-develop.xml
  path: tmp/logs

spring:
  jackson:
    mapper.default_view_inclusion: false
    serialization:
      write_dates_as_timestamps: false
      write_bigdecimal_as_plain: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chords
    username: chords_api
    password: chords_api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        format_sql: false
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
  data:
    solr:
      host: http://localhost:8983/solr/chords-core
security:
  oauth2:
    client:
      clientId: 1086354088118124
      clientSecret: 4a3ec7f1dae4e2e3c49c44e8d3daf2cf
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      use-current-uri: false
      pre-established-redirect-uri: http://localhost:3000
    resource:
      userInfoUri: https://graph.facebook.com/me

flyway:
  db:
    clean: ${flyway.clean:false}

endpoints.enabled: false

endpoints:
  info.enabled: true
  health.enabled: true



