SET NAMES 'utf8';

DROP TABLE IF EXISTS `diff`;

CREATE TABLE `diff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `diff` TEXT NOT NULL,
  `song_id`INT(11) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;